// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteApp.Data;

#nullable disable

namespace RestauranteApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212231143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("RestauranteApp.Data.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RestauranteApp.Data.Combo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Almuerzo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cena")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Desayuno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ComboId");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("RestauranteApp.Data.Consumo", b =>
                {
                    b.Property<int>("ConsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("DATE");

                    b.Property<int>("SuscripcionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConsumoId");

                    b.HasIndex("SuscripcionId", "Dia", "Tipo")
                        .IsUnique();

                    b.ToTable("Consumos");
                });

            modelBuilder.Entity("RestauranteApp.Data.Suscripcion", b =>
                {
                    b.Property<int>("SuscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComboId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("DATE");

                    b.HasKey("SuscripcionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ComboId");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("RestauranteApp.Data.Consumo", b =>
                {
                    b.HasOne("RestauranteApp.Data.Suscripcion", "Suscripcion")
                        .WithMany("Consumos")
                        .HasForeignKey("SuscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suscripcion");
                });

            modelBuilder.Entity("RestauranteApp.Data.Suscripcion", b =>
                {
                    b.HasOne("RestauranteApp.Data.Cliente", "Cliente")
                        .WithMany("Suscripciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteApp.Data.Combo", "Combo")
                        .WithMany("Suscripciones")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Combo");
                });

            modelBuilder.Entity("RestauranteApp.Data.Cliente", b =>
                {
                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("RestauranteApp.Data.Combo", b =>
                {
                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("RestauranteApp.Data.Suscripcion", b =>
                {
                    b.Navigation("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
